import type { useRouter } from 'expo-router'

type Router = ReturnType<typeof useRouter>

/**
 * Opens a thread screen. Object hrefs are used throughout rather than
 * strings: the typed-routes union in `.expo/types` is regenerated by
 * `expo start`, not `tsc`, so string hrefs go stale on a fresh checkout.
 */
export function openThread(router: Router, thread: { id: string; project_id: string }): void {
  router.push({ pathname: '/thread/[threadId]', params: { threadId: thread.id, projectId: thread.project_id } })
}

/** Opens the New-thread sheet, optionally preselecting a project. */
export function openNewThread(router: Router, projectId?: string): void {
  router.push({ pathname: '/new-thread', params: projectId ? { projectId } : {} })
}
