/**
 * The single source of truth for request/response channels.
 *
 * `local` means Electron renderer IPC can invoke the channel.
 * `remote` means the control RPC transport can invoke the channel.
 *
 * Argument and result types live in the exhaustive `ChannelContract` interface.
 * Desktop and mobile adapters derive their callable interfaces from that contract.
 */
export const CHANNEL_REGISTRY = {
  'projects:list': { local: true, remote: true },
  'projects:listArchived': { local: true, remote: true },
  'projects:favicon': { local: true, remote: true },
  'projects:create': { local: true, remote: true },
  'projects:createFull': { local: true, remote: true },
  'projects:update': { local: true, remote: true },
  'projects:delete': { local: true, remote: true },
  'projects:archive': { local: true, remote: true },
  'projects:unarchive': { local: true, remote: true },
  'locations:list': { local: true, remote: true },
  'locations:pathExists': { local: true, remote: true },
  'locations:create': { local: true, remote: true },
  'locations:update': { local: true, remote: true },
  'locations:delete': { local: true, remote: true },
  'locations:createWorktree': { local: true, remote: true },
  'locations:removeWorktree': { local: true, remote: true },
  'locations:clone': { local: true, remote: true },
  'locations:suggestPath': { local: true, remote: true },
  'locations:checkout': { local: true, remote: true },
  'locations:returnToPool': { local: true, remote: true },
  'location-pools:list': { local: true, remote: true },
  'location-pools:create': { local: true, remote: true },
  'location-pools:update': { local: true, remote: true },
  'location-pools:delete': { local: true, remote: true },
  'ssh:test': { local: true, remote: true },
  'wsl:test': { local: true, remote: true },
  'wsl:list-distros': { local: true, remote: true },
  'threads:list': { local: true, remote: true },
  'threads:listQueue': { local: true, remote: true },
  'threads:listQueueArchived': { local: true, remote: true },
  'threads:listQueueSnoozed': { local: true, remote: true },
  'threads:create': { local: true, remote: true },
  'threads:delete': { local: true, remote: true },
  'threads:archivedCount': { local: true, remote: true },
  'threads:listArchived': { local: true, remote: true },
  'threads:archive': { local: true, remote: true },
  'threads:unarchive': { local: true, remote: true },
  'threads:snoozedCount': { local: true, remote: true },
  'threads:listSnoozed': { local: true, remote: true },
  'threads:snooze': { local: true, remote: true },
  'threads:unsnooze': { local: true, remote: true },
  'threads:updateName': { local: true, remote: true },
  'threads:updateModel': { local: true, remote: true },
  'threads:updateProviderAndModel': { local: true, remote: true },
  'threads:updateReasoningLevel': { local: true, remote: true },
  'threads:updateCodexPersonality': { local: true, remote: true },
  'threads:updateCodexReasoningSummary': { local: true, remote: true },
  'threads:updateCursorThinking': { local: true, remote: true },
  'threads:updateCursorContext': { local: true, remote: true },
  'threads:setUnread': { local: true, remote: true },
  'threads:setYolo': { local: true, remote: true },
  'threads:setPermissionMode': { local: true, remote: true },
  'threads:setWsl': { local: true, remote: true },
  'threads:start': { local: true, remote: true },
  'threads:stop': { local: true, remote: true },
  'threads:backgroundTerminals:list': { local: true, remote: true },
  'threads:backgroundTerminals:terminate': { local: true, remote: true },
  'threads:backgroundTerminals:clean': { local: true, remote: true },
  'threads:reset': { local: true, remote: true },
  'threads:getPid': { local: true, remote: true },
  'threads:send': { local: true, remote: true, originAware: true },
  'threads:approvePlan': { local: true, remote: true },
  'threads:rejectPlan': { local: true, remote: true },
  'threads:getQuestions': { local: true, remote: true },
  'threads:answerQuestion': { local: true, remote: true },
  'threads:getPendingPermissions': { local: true, remote: true },
  'threads:approvePermissions': { local: true, remote: true },
  'threads:denyPermissions': { local: true, remote: true },
  'threads:executePlanInNewContext': { local: true, remote: true },
  'threads:getModifiedFiles': { local: true, remote: true },
  'threads:getLogs': { local: true, remote: true },
  'sessions:list': { local: true, remote: true },
  'sessions:getActive': { local: true, remote: true },
  'sessions:switch': { local: true, remote: true },
  'messages:list': { local: true, remote: true },
  'messages:listBySession': { local: true, remote: true },
  'git:branch': { local: true, remote: true },
  'git:status': { local: true, remote: true },
  'git:head': { local: true, remote: true },
  'git:commit': { local: true, remote: true },
  'git:lastCommit': { local: true, remote: true },
  'git:amendCommit': { local: true, remote: true },
  'git:undoLastCommit': { local: true, remote: true },
  'git:stage': { local: true, remote: true },
  'git:unstage': { local: true, remote: true },
  'git:stageAll': { local: true, remote: true },
  'git:unstageAll': { local: true, remote: true },
  'git:stageFiles': { local: true, remote: true },
  'git:discardFile': { local: true, remote: true },
  'git:discardFiles': { local: true, remote: true },
  'git:discardAll': { local: true, remote: true },
  'git:generateCommitMessage': { local: true, remote: true },
  'git:generateCommitMessageWithContext': { local: true, remote: true },
  'git:generatePullRequestText': { local: true, remote: true },
  'git:generateBranchName': { local: true, remote: true },
  'git:push': { local: true, remote: true },
  'git:publishBranch': { local: true, remote: true },
  'git:pushSetUpstream': { local: true, remote: true },
  'git:pull': { local: true, remote: true },
  'git:pullOrigin': { local: true, remote: true },
  'git:stashList': { local: true, remote: true },
  'git:stashCreate': { local: true, remote: true },
  'git:stashApply': { local: true, remote: true },
  'git:stashPop': { local: true, remote: true },
  'git:stashDrop': { local: true, remote: true },
  'git:forceUnlock': { local: true, remote: true },
  'git:fetchRemote': { local: true, remote: true },
  'git:diff': { local: true, remote: true },
  'git:compareToMain': { local: true, remote: true },
  'git:compareDiffToMain': { local: true, remote: true },
  'git:compareToBranch': { local: true, remote: true },
  'git:compareDiffToBranch': { local: true, remote: true },
  'git:log': { local: true, remote: true },
  'git:commitFiles': { local: true, remote: true },
  'git:commitDiff': { local: true, remote: true },
  'git:branches': { local: true, remote: true },
  'git:watchStart': { local: true, remote: true },
  'git:watchStop': { local: true, remote: true },
  'git:checkout': { local: true, remote: true },
  'git:createBranch': { local: true, remote: true },
  'git:merge': { local: true, remote: true },
  'git:findMergedBranches': { local: true, remote: true },
  'git:deleteBranches': { local: true, remote: true },
  'git:init': { local: true, remote: true },
  'git:isRepo': { local: true, remote: true },
  'git:getRemoteUrl': { local: true, remote: true },
  'git:hostingProvider': { local: true, remote: true },
  'git:defaultBranch': { local: true, remote: true },
  'forge:pr:list': { local: true, remote: true },
  'forge:pr:enrich': { local: true, remote: true },
  'forge:pr:current': { local: true, remote: true },
  'forge:pr:create': { local: true, remote: true },
  'forge:pr:checkout': { local: true, remote: true },
  'forge:pr:webUrl': { local: true, remote: true },
  'forge:repo:webUrl': { local: true, remote: true },
  'files:list': { local: true, remote: true },
  'files:read': { local: true, remote: true },
  'files:searchList': { local: true, remote: true },
  'files:watchStart': { local: true, remote: true },
  'files:watchStop': { local: true, remote: true },
  'claude-history:listProjects': { local: true, remote: true },
  'claude-history:listSessions': { local: true, remote: true },
  'claude-history:importedIds': { local: true, remote: true },
  'claude-history:import': { local: true, remote: true },
  'commands:list': { local: true, remote: true },
  'commands:create': { local: true, remote: true },
  'commands:update': { local: true, remote: true },
  'commands:delete': { local: true, remote: true },
  'commands:start': { local: true, remote: true },
  'commands:stop': { local: true, remote: true },
  'commands:restart': { local: true, remote: true },
  'commands:getStatus': { local: true, remote: true },
  'commands:getLogs': { local: true, remote: true },
  'commands:getPid': { local: true, remote: true },
  'commands:getPorts': { local: true, remote: true },
  'youtrack:servers:list': { local: true, remote: true },
  'youtrack:servers:create': { local: true, remote: true },
  'youtrack:servers:update': { local: true, remote: true },
  'youtrack:servers:delete': { local: true, remote: true },
  'youtrack:test': { local: true, remote: true },
  'youtrack:search': { local: true, remote: true },
  'terminal:spawn': { local: true, remote: true },
  'terminal:write': { local: true, remote: true },
  'terminal:resize': { local: true, remote: true },
  'terminal:kill': { local: true, remote: true },
  'terminal:getBuffer': { local: true, remote: true },
  'attachments:save': { local: true, remote: true },
  'attachments:cleanup': { local: true, remote: true },
  'attachments:readDataUrl': { local: false, remote: true },
  'plans:getForThread': { local: false, remote: true },
  'process:kill': { local: true, remote: true },
  'cli:health': { local: true, remote: true },
  'cli:update': { local: true, remote: true },
  'models:claudeAvailable': { local: true, remote: true },
  'models:codexAvailable': { local: true, remote: true },
  'models:opencodeAvailable': { local: true, remote: true },
  'models:piAvailable': { local: true, remote: true },
  'models:cursorAvailable': { local: true, remote: true },
  'models:grokAvailable': { local: true, remote: true },
  // Routine management is desktop-only in v1; escalated runs surface through
  // the normal thread channels, so mobile sees them with no extra plumbing.
  'routines:list': { local: true, remote: false },
  'routines:create': { local: true, remote: false },
  'routines:update': { local: true, remote: false },
  'routines:delete': { local: true, remote: false },
  'routines:setEnabled': { local: true, remote: false },
  'routines:runNow': { local: true, remote: false },
  'routines:listRuns': { local: true, remote: false },
  'routines:dismissRun': { local: true, remote: false },
  'routines:runHasUnshippedWork': { local: true, remote: false },
  'slash-commands:list': { local: true, remote: true },
  'skills:list': { local: true, remote: true },
  'slash-commands:create': { local: true, remote: true },
  'slash-commands:update': { local: true, remote: true },
  'slash-commands:delete': { local: true, remote: true },
  'app:getVersion': { local: true, remote: false },
  'app:open-logs-folder': { local: true, remote: false },
  'attachments:getFileInfo': { local: true, remote: false },
  'attachments:saveFromPath': { local: true, remote: false },
  'dialog:open-directory': { local: true, remote: false },
  'dialog:open-files': { local: true, remote: false },
  'settings:get': { local: true, remote: false },
  'settings:set': { local: true, remote: false },
  'shell:copyPath': { local: true, remote: false },
  'shell:openInExplorer': { local: true, remote: false },
  'shell:openInTerminal': { local: true, remote: false },
  'shell:openInVsCode': { local: true, remote: false },
  'shell:revealInExplorer': { local: true, remote: false },
  'update:apply': { local: true, remote: false },
  'update:check': { local: true, remote: false },
  'update:get-state': { local: true, remote: false },
  'webhook:getConfig': { local: true, remote: false },
  'webhook:setConfig': { local: true, remote: false },
  'remote:getServerConfig': { local: true, remote: false },
  'remote:setServerConfig': { local: true, remote: false },
  'remote:regenerateServerToken': { local: true, remote: false },
  'remote:getHosts': { local: true, remote: false },
  'remote:addHost': { local: true, remote: false },
  'remote:updateHost': { local: true, remote: false },
  'remote:removeHost': { local: true, remote: false },
  'remote:setActiveHost': { local: true, remote: false },
  'remote:getActiveHost': { local: true, remote: false },
  'remote:testHost': { local: true, remote: false },
  'remote:getPairingInfo': { local: true, remote: false },
  'window:close': { local: true, remote: false },
  'window:is-maximized': { local: true, remote: false },
  'window:maximize': { local: true, remote: false },
  'window:minimize': { local: true, remote: false },
} as const

export type Channel = keyof typeof CHANNEL_REGISTRY
export type RemoteChannel = {
  [C in Channel]: (typeof CHANNEL_REGISTRY)[C]['remote'] extends true ? C : never
}[Channel]
export type LocalChannel = {
  [C in Channel]: (typeof CHANNEL_REGISTRY)[C]['local'] extends true ? C : never
}[Channel]

export const REMOTE_CHANNELS = Object.freeze(
  (Object.keys(CHANNEL_REGISTRY) as Channel[]).filter(
    (channel): channel is RemoteChannel => CHANNEL_REGISTRY[channel].remote,
  ),
)

const REMOTE_CHANNEL_SET: ReadonlySet<string> = new Set(REMOTE_CHANNELS)

export function isRemoteChannel(channel: string): channel is RemoteChannel {
  return REMOTE_CHANNEL_SET.has(channel)
}

export const LOCAL_CHANNELS = Object.freeze(
  (Object.keys(CHANNEL_REGISTRY) as Channel[]).filter(
    (channel): channel is LocalChannel => CHANNEL_REGISTRY[channel].local,
  ),
)

const LOCAL_CHANNEL_SET: ReadonlySet<string> = new Set(LOCAL_CHANNELS)

export function isLocalChannel(channel: string): channel is LocalChannel {
  return LOCAL_CHANNEL_SET.has(channel)
}
