import type { ChannelArgs, ChannelResult, RemoteChannel } from '@polycode/shared'
import { rpcRequest, type HostConnection } from './client'

/** Remote channels intentionally exposed by the mobile adapter. */
export const MOBILE_RPC_CHANNELS = [
  'projects:list',
  'projects:create',
  'projects:createFull',
  'projects:update',
  'projects:delete',
  'projects:archive',
  'projects:unarchive',
  'locations:list',
  'locations:create',
  'locations:update',
  'locations:delete',
  'locations:createWorktree',
  'locations:removeWorktree',
  'locations:clone',
  'locations:suggestPath',
  'location-pools:list',
  'location-pools:create',
  'location-pools:update',
  'location-pools:delete',
  'ssh:test',
  'wsl:test',
  'wsl:list-distros',
  'threads:list',
  'threads:create',
  'threads:delete',
  'threads:archive',
  'threads:unarchive',
  'threads:archivedCount',
  'threads:listArchived',
  'threads:updateName',
  'threads:updateProviderAndModel',
  'threads:updateReasoningLevel',
  'threads:updateCursorThinking',
  'threads:updateCursorContext',
  'threads:setUnread',
  'threads:setPermissionMode',
  'threads:start',
  'threads:stop',
  'threads:reset',
  'threads:send',
  'threads:approvePlan',
  'threads:rejectPlan',
  'threads:executePlanInNewContext',
  'threads:getQuestions',
  'threads:answerQuestion',
  'threads:getPendingPermissions',
  'threads:approvePermissions',
  'threads:denyPermissions',
  'sessions:list',
  'sessions:getActive',
  'sessions:switch',
  'messages:list',
  'messages:listBySession',
  'slash-commands:list',
  'attachments:save',
  'attachments:readDataUrl',
  'plans:getForThread',
  'git:branch',
  'git:status',
  'git:commit',
  'git:lastCommit',
  'git:stage',
  'git:unstage',
  'git:stageAll',
  'git:unstageAll',
  'git:discardFile',
  'git:generateCommitMessage',
  'git:push',
  'git:pushSetUpstream',
  'git:pull',
  'git:watchStart',
  'git:watchStop',
  'files:list',
  'files:read',
  'claude-history:listProjects',
  'claude-history:listSessions',
  'claude-history:importedIds',
  'claude-history:import',
  'commands:list',
  'commands:start',
  'commands:stop',
  'commands:restart',
  'commands:getStatus',
  'commands:getLogs',
  'commands:getPorts',
  'youtrack:servers:list',
  'youtrack:servers:create',
  'youtrack:servers:update',
  'youtrack:servers:delete',
  'youtrack:test',
  'youtrack:search',
  'models:claudeAvailable',
  'models:codexAvailable',
  'models:opencodeAvailable',
  'models:piAvailable',
  'models:cursorAvailable',
] as const satisfies readonly RemoteChannel[]

export type RpcChannel = (typeof MOBILE_RPC_CHANNELS)[number]

/** Typed RPC call against a specific host. */
export function rpc<C extends RpcChannel>(
  host: HostConnection,
  channel: C,
  ...args: ChannelArgs<C>
): Promise<ChannelResult<C>> {
  return rpcRequest(host, channel, args) as Promise<ChannelResult<C>>
}
